// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc7vjxlyaeOCOnIQjQ_eoSmgeXN1qB3yY',
    appId: '1:344917628084:web:f61c214da948b0f4c8b3e1',
    messagingSenderId: '344917628084',
    projectId: 'urban-gardening-113b6',
    authDomain: 'urban-gardening-113b6.firebaseapp.com',
    storageBucket: 'urban-gardening-113b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwy2Qp3z7mmCQ54TksFFvocF1Y4XnfUu0',
    appId: '1:344917628084:android:b251220a13b7002ec8b3e1',
    messagingSenderId: '344917628084',
    projectId: 'urban-gardening-113b6',
    storageBucket: 'urban-gardening-113b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSmcTAqwVXBbL2AH8eY1pEEtMMAOgVrWg',
    appId: '1:344917628084:ios:56e11fdb5f931d26c8b3e1',
    messagingSenderId: '344917628084',
    projectId: 'urban-gardening-113b6',
    storageBucket: 'urban-gardening-113b6.appspot.com',
    iosBundleId: 'com.example.urbanGardening',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSmcTAqwVXBbL2AH8eY1pEEtMMAOgVrWg',
    appId: '1:344917628084:ios:56e11fdb5f931d26c8b3e1',
    messagingSenderId: '344917628084',
    projectId: 'urban-gardening-113b6',
    storageBucket: 'urban-gardening-113b6.appspot.com',
    iosBundleId: 'com.example.urbanGardening',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc7vjxlyaeOCOnIQjQ_eoSmgeXN1qB3yY',
    appId: '1:344917628084:web:cc7008b37589c1e2c8b3e1',
    messagingSenderId: '344917628084',
    projectId: 'urban-gardening-113b6',
    authDomain: 'urban-gardening-113b6.firebaseapp.com',
    storageBucket: 'urban-gardening-113b6.appspot.com',
  );
}
