// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0OEkqa2jOWeB4m0XvlfzYmZckm8FytlE',
    appId: '1:461246911859:web:30823a393b6ddbcd156106',
    messagingSenderId: '461246911859',
    projectId: 'my-urban-app',
    authDomain: 'my-urban-app.firebaseapp.com',
    storageBucket: 'my-urban-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiyb_OjAGJkcIV0E60VWfnTPSafUQVU34',
    appId: '1:461246911859:android:70170859650473dc156106',
    messagingSenderId: '461246911859',
    projectId: 'my-urban-app',
    storageBucket: 'my-urban-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvPQ-M5bmY9WZaie8kkX6wW5VyBZOYDAQ',
    appId: '1:461246911859:ios:774af3a765be4e64156106',
    messagingSenderId: '461246911859',
    projectId: 'my-urban-app',
    storageBucket: 'my-urban-app.appspot.com',
    iosBundleId: 'com.example.urbanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvPQ-M5bmY9WZaie8kkX6wW5VyBZOYDAQ',
    appId: '1:461246911859:ios:774af3a765be4e64156106',
    messagingSenderId: '461246911859',
    projectId: 'my-urban-app',
    storageBucket: 'my-urban-app.appspot.com',
    iosBundleId: 'com.example.urbanapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0OEkqa2jOWeB4m0XvlfzYmZckm8FytlE',
    appId: '1:461246911859:web:75bee7623386041a156106',
    messagingSenderId: '461246911859',
    projectId: 'my-urban-app',
    authDomain: 'my-urban-app.firebaseapp.com',
    storageBucket: 'my-urban-app.appspot.com',
  );
}
